### ISSUE TITLE
cKDTree for spatial neighbor search

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#23]
Explore is cKDTree can be used instead of the distanceBox method for spatial neighbor search within a search radius.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html#scipy.spatial.cKDTree

**Comment by marshuang80** [comment]
cKDTree does not significantly improve the time to search for spatial neighbors
