### ISSUE TITLE
pyarrow instead of pandas  for msgpack

### ISSUE THREAD

**Issue by yhgon** [sbl-sdsc/mmtf-pyspark#290]
pandas.read_msgpack was depreciated since pandas 0.25.0. 
So  stuck in  pandas 0.23.0

If we move to pyarrow, its faster than pandas and could avoid dependency issue for other modules.

https://pandas.pydata.org/pandas-docs/version/0.25.3/reference/api/pandas.read_msgpack.html

https://github.com/pandas-dev/pandas/issues/27722

**Comment by pwrose** [comment]
@yhgon Do you have an idea of how to do this with pyarrow?

**Comment by dkoes** [comment]
Why isn't the `msgpack` package used directly?  I see its use commented out in the code, but the deprecated pd.read_msgpack is used instead.  The current package version requirements are painfully old (e.g., the desired version of anaconda doesn't exist for an ARM Mac that I can see) and we're have difficulty installing.  However, if I switch to msgpack `test_mmtfPyspark.py` at least seems to work using the latest version of all the dependencies.

**Comment by pwrose** [comment]
pd.read_msgpack was faster than the original msgpack package. Do you want
to make a pull request with the updated dependencies?

**Comment by pwrose** [comment]
Now using the latest version of msgpack.
