### ISSUE TITLE
Hosting sample files in a separate Git repo

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#30]
We should consider hosting sample files in a separate Git repo (e.g., mmtf-samples).

For the binder setup, we should be able to download the data in the postBuild file (see: https://media.readthedocs.org/pdf/mybinder/latest/mybinder.pdf):

curl -O -L https://github.com/sbl-sdsc/mmtf-samples/raw/master/resources/mmtf_full_sample/part-0000[0-7]
mkdir mmtf_full_sample
mv part-0000* ./mmtf_full_sample

**Comment by marshuang80** [comment]
Since we uploaded the new sample subset on both repositories, should we close this issue?

**Comment by pwrose** [comment]
yes

**Comment by marshuang80** [comment]
fixed with commit f975a9573f08ce56cb9ba6985463c0a84d5ac2a5
