### ISSUE TITLE
Upgrade to Spark 2.3.0

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#47]
The download script has an old version 2.1.0.

**Comment by marshuang80** [comment]
Postpone till after workshop

**Comment by marshuang80** [comment]
fixed with commit 259ce67ba5589f4b35de4d223526a6a8c419b59e

**Comment by marshuang80** [comment]
fixed with commit 259ce67ba5589f4b35de4d223526a6a8c419b59e
