### ISSUE TITLE
[!] structureviewer.view_structure

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#49]
if the input contains a chain id, change:

            viewer.setStyle({'hetflag': True},{'stick':{'singleBond':False}}) -->
           viewer.setStyle({'chain': chainid, 'hetflag': True},{'stick':{'singleBond':False}}) 

pdbid,chainid = pdbIds[i].split('.')
            viewer = py3Dmol.view(query='pdb:' + pdbid, options={'doAssembly': bioAssembly})
            viewer.setStyle({})
            viewer.setStyle({'chain': chainid}, {style: {'color': color}})
            viewer.setStyle({'hetflag': True},{'stick':{'singleBond':False}})
            viewer.zoomTo({'chain': chainid})

**Comment by marshuang80** [comment]
Fixed with commit 0565eb3aed75dadec3aaf7651ea5920b8f947d89

**Comment by marshuang80** [comment]
0565eb3aed75dadec3aaf7651ea5920b8f947d89
