### ISSUE TITLE
[!] traverseStructureHierarchy.print_chain_entity_group_atom_info

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#58]
The alt_loc_list is accessed, but not initialized. Also, check other methods in this file to make sure alt_locs are initialized.

~/anaconda3/lib/python3.6/site-packages/mmtfPyspark/utils/traverseStructureHierarchy.py in print_chain_entity_group_atom_info(structure)
    205                 for m in range(0, (len(structure.group_list[groupType]["atomNameList"]))):
    206                     atomId = structure.atom_id_list[atomIndex]
--> 207                     altLocId = structure.alt_loc_list[atomIndex]
    208                     x = structure.x_coord_list[atomIndex]
    209                     y = structure.y_coord_list[atomIndex]

**Comment by marshuang80** [comment]
Fixed with commit 730b26d6f1427ff55ce67d99f261fa6b416c2ed3
