### ISSUE TITLE
Increase reliability of customReportService

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#68]
Try the following urls if an error occurs anywhere in this block of code below.

Also use https instead of http.

1. https://www.rcsb.org/...
2.https://www2.rcsb..org/...
3. https://www1.rcsb.org/...

-----------------
    ```
query = CURRENT_URL + ','.join(columnNames)
    inStream = _post_query(query)

    tmp = tempfile.NamedTemporaryFile(delete=False)

    with open(tmp.name, "w") as t:
        for l in inStream:
            t.writelines(str(l)[2:-3] + '\n')

    spark = SparkSession.builder.getOrCreate()

    dataset = _read_csv(spark, tmp.name)
```

**Comment by marshuang80** [comment]
fixed by commit 19b8bbadbd0bfcc4b0059de35d6065e20cf0c0bf
