### ISSUE TITLE
curl, add -k option for Windows installation

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/mmtf-pyspark#70]
C:\Users\Peter\mmtf-pyspark>curl https://raw.githubusercontent.com/sbl-sdsc/mmtf-pyspark/master/test_mmtfPyspark.py -o test_mmtfPyspark.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

C:\Users\Peter\mmtf-pyspark>ls
mmtf-pyspark

C:\Users\Peter\mmtf-pyspark>python test_mmtfPyspark.py
python: can't open file 'test_mmtfPyspark.py': [Errno 2] No such file or directory

C:\Users\Peter\mmtf-pyspark>ls
mmtf-pyspark

C:\Users\Peter\mmtf-pyspark>curl -k https://raw.githubusercontent.com/sbl-sdsc/mmtf-pyspark/master/test_mmtfPyspark.py -o test_mmtfPyspark.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   540  100   540    0     0    548      0 --:--:-- --:--:-- --:--:--   548

**Comment by marshuang80** [comment]
Is this for all the links or just for test_mmtfPyspark?

**Comment by marshuang80** [comment]
closed with commit d35741d8e43cb0e815a0b1e3a5fa349685137c09
