### ISSUE TITLE
Notebook conversion for ReadTheDocs

### ISSUE THREAD

**Issue by fsimkovic** [sbl-sdsc/mmtf-pyspark#85]
Original issue raised by @marshuang80 described in #84 

------

I am wondering if it is possible to get our examples to point directly to our github demos folder instead of having two different copies of them? Those demos are still subject to change and maintenance, so it will be a lot more convenient if we can just use our original notebooks in the demos folder.

So far I have tried to create a symbolic link in `_static` that points to the demos folder from the main directory, and I was able to open the notebooks from the webpage locally. However, at all cell blocks where plots are supposed to be displayed, I got the path to the image instead. eg: `file:///my_path_to_mmtfPyspark/mmtf-pyspark/docs/_build/html/_static/demo/applications/_build/doctrees/nbsphinx/_static_demo_applications_MetalInteractionsAdvanced_14_0.png`

**Comment by fsimkovic** [comment]
We can fix the build locally by copying the `demos` directory across using something like below in the `docs/conf.py`.

```python
include_directories = [                                                                                                 
    '../demos',                                                                                                         
]                                                                                                                       
for directory in include_directories:                                                                                   
    assert os.path.isfile(directory), "Cannot find directory %s" % directory                                            
    clone = directory.replace("..", ".")                                                                                
    if os.path.isdir(clone):                                                                                            
        shutil.rmtree(clone)                                                                                            
    shutil.copytree(directory, clone) 
```

This causes a number of issues though on ReadTheDocs ... see [this build attempt](https://readthedocs.org/projects/mmtf-pyspark-test/builds/7197374/), which basically raises the following exception

```python-traceback
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mmtf-pyspark-test/envs/latest/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mmtf-pyspark-test/envs/latest/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 60, in <module>
    assert os.path.isfile(directory), "Cannot find directory %s" % directory
AssertionError: Cannot find directory ../demos
```
This suggests to me that a symlink won't work either and we need to fix the issue differently.

The second issue with regards to the narrow visualisation of 3Dmol.js appears to be caused by the `overflow: auto` CSS style applied to the `div="output_area"` blocks. We might have to consult with the `nbsphinx` developers to find a work-around.

**Comment by fsimkovic** [comment]
The download can be fixed by generating Python scripts locally and dumping them alongside the notebooks in the `demos`. I used the following command in root to generate all of them:

```bash
for nb in $(ls demos/*/*.ipynb | xargs); 
do 
    jupyter nbconvert --to=python --output=${nb}.py --output-dir=. $nb; 
done
```

We can then download the files via [rawgit](https://rawgit.com/) using this `nbsphinx_epilog`

```python
nbsphinx_epilog = """                                                                                                   
                                                                                                                        
.. raw:: html                                                                                                           
                                                                                                                        
   {% set rawgitbase = 'https://cdn.rawgit.com/sbl-sdsc/mmtf-pyspark/3757cfde' %}                                       
   {% set rawgiturl = env.doc2path(env.docname, base=rawgitbase) %}                                                     
                                                                                                                        
   <div class="btn-container">                                                                                          
       <a class="btn btn-download" role="button" href="{{ rawgiturl }} " download>Download Notebook</a>                 
       <a class="btn btn-download" role="button" href="{{ rawgiturl }}.py" download>Download Script</a>                 
   </div>                                                                                                               
                                                                                                                        
"""
```

This was implemented in https://github.com/fsimkovic/mmtf-pyspark/commit/4d025a3e645df1425f06de752b49b5f7bed82214

**Comment by fsimkovic** [comment]
Detected incorrect function call in `assert` statement, corrected to `assert os.path.isdir(directory)` in https://github.com/fsimkovic/mmtf-pyspark/commit/0889379c199b0648ee9d910f786df267e97ca1d1 which resolves the failed build.

A successful ReadTheDocs build can be found [here](https://readthedocs.org/projects/mmtf-pyspark-test/builds/7197517/) and the website [here](https://mmtf-pyspark-test.readthedocs.io/)

**Comment by fsimkovic** [comment]
I believe this resolves the issue? @marshuang80 could you confirm?

**Comment by marshuang80** [comment]
This is exactly what I was looking for, thank you @fsimkovic. Please go ahead and submit a pull request.

**Comment by fsimkovic** [comment]
I will submit one overall PR to also address the other outstanding issue. I think both are now combined so it makes sense to close it together.

**Comment by marshuang80** [comment]
Looking back to the commit history, it seems like the ```IPython.core.display.HTML object``` line was added to after I saved the widget state of the notebook. However, I couldn't replicate the result with the other notebooks.

**Comment by pwrose** [comment]
We will revisit notebook conversion at another time.
