### ISSUE TITLE
Width-limited 3Dmol visualisation with nbsphinx

### ISSUE THREAD

**Issue by fsimkovic** [sbl-sdsc/mmtf-pyspark#86]
Original issue raised by @marshuang80 described in #84 

------

I also realized that pointing to the original notebooks allowed our 3D visualization to work, but in the very long and narrow window all the way on the left side shown in the figure below. Any idea how to fix this?

Example can be viewed in the [MetalInteractionsAdvanced notebook](https://mmtf-pyspark-test.readthedocs.io/en/latest/demos/applications/MetalInteractionsAdvanced.html#Visualize-Data)

**Comment by fsimkovic** [comment]
The narrow visualisation of 3Dmol.js appears to be caused by the `overflow: auto` CSS style applied to the `div="output_area"` blocks. We might have to consult with the `nbsphinx` developers to find a work-around.

**Comment by fsimkovic** [comment]
Issue referred to nbsphinx page https://github.com/spatialaudio/nbsphinx/issues/186.

**Comment by marshuang80** [comment]
@fsimkovic, I realized that simply pointing to the original notebooks won't allow our 3D visualizations to work. For example, the [PDB Drug Bank Mapping Example](http://mmtf-pyspark.readthedocs.io/en/latest/_static/demos/applications/PdbDrugBankMapping.html) is currently pointed to the original notebook, but it does not have any visualization output as we desired. Do you know if there is a step I am missing, perheps to convert the notebooks using nbsphinx?

Comparing the two different notebook's source code, I realized that they have a different output format for their visualization cell blocks.
- Cell block with working visualisation: 
```
 "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
```

- Cell block without working visualisation:
```
      "text/plain": [
       "interactive(children=(IntSlider(value=0, continuous_update=False, description='Structure', max=171), Output())…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
```

I have tried to save the widget state of the jupyter notebook, but it just prints a lot of junk at the end of the webpage: 
![image](https://user-images.githubusercontent.com/15271135/40141039-5b4a1b52-5909-11e8-96db-4f4fcba3add1.png)

**Comment by fsimkovic** [comment]
:thinking: I get the same ... how did we generate [MetalInteractionsAdvanced notebook](https://mmtf-pyspark-test.readthedocs.io/en/latest/demos/applications/MetalInteractionsAdvanced.html#Visualize-Data)? Do you remember?

**Comment by pwrose** [comment]
Try adding this in a cell before the visualization cell:

%%javascript 
IPython.OutputArea.prototype._should_scroll = function(lines) {return false;}

**Comment by fsimkovic** [comment]
Thanks for the tip but we actually cannot reproduce how we saved the notebook linked above. This basically means none of the widgets/graphics work at the moment for any of the notebooks and instead we see this random text at the end of each notebook.

**Comment by pwrose** [comment]
Will revisit visualization issues in nbsphinx in the future.
